export type {
  AdminStats,
  AdminStatsRecentAppointment,
  AdminStatsRatingBucket,
  AdminStatsStatusCount,
  AdminStatsTopMentor,
  AdminStatsTrendPoint,
  Appointment,
  AppointmentJoinResponse,
  AppointmentRating,
  AppointmentStatusValue,
  AreaOfExpertise,
  AvailableSlot,
  BookAppointmentInput,
  BookingMentor,
  MentorProfile,
  RateAppointmentInput,
  SlotFilters,
} from '@/modules/appointment/types/appointment.types'
