/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotModulesAppLayoutsPublicRouteImport } from './modules/app/layouts/_public'
import { Route as DotDotModulesAppLayoutsPanelRouteImport } from './modules/app/layouts/_panel'
import { Route as IndexRouteImport } from './modules/app/routes/public/index'
import { Route as AboutRouteImport } from './modules/app/routes/panel/about'
import { Route as BooksIndexRouteImport } from './modules/book/routes/index'
import { Route as BooksUpsertIndexRouteImport } from './modules/book/routes/upsert/index'
import { Route as BooksBookIdIndexRouteImport } from './modules/book/routes/bookId/index'
import { Route as BooksUpsertBookIdRouteImport } from './modules/book/routes/upsert/bookId'

const DotDotModulesAppLayoutsPublicRoute =
  DotDotModulesAppLayoutsPublicRouteImport.update({
    id: '/_public',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotModulesAppLayoutsPanelRoute =
  DotDotModulesAppLayoutsPanelRouteImport.update({
    id: '/_panel',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const BooksUpsertIndexRoute = BooksUpsertIndexRouteImport.update({
  id: '/books/upsert/',
  path: '/books/upsert/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const BooksBookIdIndexRoute = BooksBookIdIndexRouteImport.update({
  id: '/books/bookId/',
  path: '/books/bookId/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const BooksUpsertBookIdRoute = BooksUpsertBookIdRouteImport.update({
  id: '/books/upsert/bookId',
  path: '/books/upsert/bookId',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books/': typeof BooksIndexRoute
  '/books/upsert/bookId': typeof BooksUpsertBookIdRoute
  '/books/bookId/': typeof BooksBookIdIndexRoute
  '/books/upsert/': typeof BooksUpsertIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksIndexRoute
  '/books/upsert/bookId': typeof BooksUpsertBookIdRoute
  '/books/bookId': typeof BooksBookIdIndexRoute
  '/books/upsert': typeof BooksUpsertIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof DotDotModulesAppLayoutsPanelRouteWithChildren
  '/_public': typeof DotDotModulesAppLayoutsPublicRouteWithChildren
  '/_panel/about': typeof AboutRoute
  '/_public/': typeof IndexRoute
  '/_panel/books/': typeof BooksIndexRoute
  '/_panel/books/upsert/bookId': typeof BooksUpsertBookIdRoute
  '/_panel/books/bookId/': typeof BooksBookIdIndexRoute
  '/_panel/books/upsert/': typeof BooksUpsertIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books/'
    | '/books/upsert/bookId'
    | '/books/bookId/'
    | '/books/upsert/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books'
    | '/books/upsert/bookId'
    | '/books/bookId'
    | '/books/upsert'
  id:
    | '__root__'
    | '/_panel'
    | '/_public'
    | '/_panel/about'
    | '/_public/'
    | '/_panel/books/'
    | '/_panel/books/upsert/bookId'
    | '/_panel/books/bookId/'
    | '/_panel/books/upsert/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotModulesAppLayoutsPanelRoute: typeof DotDotModulesAppLayoutsPanelRouteWithChildren
  DotDotModulesAppLayoutsPublicRoute: typeof DotDotModulesAppLayoutsPublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotDotModulesAppLayoutsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotDotModulesAppLayoutsPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_panel/about': {
      id: '/_panel/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/books/': {
      id: '/_panel/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/books/upsert/': {
      id: '/_panel/books/upsert/'
      path: '/books/upsert'
      fullPath: '/books/upsert/'
      preLoaderRoute: typeof BooksUpsertIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/books/bookId/': {
      id: '/_panel/books/bookId/'
      path: '/books/bookId'
      fullPath: '/books/bookId/'
      preLoaderRoute: typeof BooksBookIdIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/books/upsert/bookId': {
      id: '/_panel/books/upsert/bookId'
      path: '/books/upsert/bookId'
      fullPath: '/books/upsert/bookId'
      preLoaderRoute: typeof BooksUpsertBookIdRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
  }
}

interface DotDotModulesAppLayoutsPanelRouteChildren {
  AboutRoute: typeof AboutRoute
  BooksIndexRoute: typeof BooksIndexRoute
  BooksUpsertBookIdRoute: typeof BooksUpsertBookIdRoute
  BooksBookIdIndexRoute: typeof BooksBookIdIndexRoute
  BooksUpsertIndexRoute: typeof BooksUpsertIndexRoute
}

const DotDotModulesAppLayoutsPanelRouteChildren: DotDotModulesAppLayoutsPanelRouteChildren =
  {
    AboutRoute: AboutRoute,
    BooksIndexRoute: BooksIndexRoute,
    BooksUpsertBookIdRoute: BooksUpsertBookIdRoute,
    BooksBookIdIndexRoute: BooksBookIdIndexRoute,
    BooksUpsertIndexRoute: BooksUpsertIndexRoute,
  }

const DotDotModulesAppLayoutsPanelRouteWithChildren =
  DotDotModulesAppLayoutsPanelRoute._addFileChildren(
    DotDotModulesAppLayoutsPanelRouteChildren,
  )

interface DotDotModulesAppLayoutsPublicRouteChildren {
  IndexRoute: typeof IndexRoute
}

const DotDotModulesAppLayoutsPublicRouteChildren: DotDotModulesAppLayoutsPublicRouteChildren =
  {
    IndexRoute: IndexRoute,
  }

const DotDotModulesAppLayoutsPublicRouteWithChildren =
  DotDotModulesAppLayoutsPublicRoute._addFileChildren(
    DotDotModulesAppLayoutsPublicRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotDotModulesAppLayoutsPanelRoute:
    DotDotModulesAppLayoutsPanelRouteWithChildren,
  DotDotModulesAppLayoutsPublicRoute:
    DotDotModulesAppLayoutsPublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
