/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotModulesAppLayoutsPublicRouteImport } from './modules/app/layouts/_public'
import { Route as DotDotModulesAppLayoutsPanelRouteImport } from './modules/app/layouts/_panel'
import { Route as IndexRouteImport } from './modules/app/routes/public/index'
import { Route as RegisterRouteImport } from './modules/auth/routes/public/register'
import { Route as LoginRouteImport } from './modules/auth/routes/public/login'
import { Route as AboutRouteImport } from './modules/app/routes/panel/about'
import { Route as UsersIndexRouteImport } from './modules/user/routes/index'
import { Route as ProfileIndexRouteImport } from './modules/auth/routes/profile/index'
import { Route as UsersUserIdIndexRouteImport } from './modules/user/routes/userId/index'
import { Route as UsersUpsertIndexRouteImport } from './modules/user/routes/upsert/index'
import { Route as UsersUpsertUserIdRouteImport } from './modules/user/routes/upsert/userId'

const DotDotModulesAppLayoutsPublicRoute =
  DotDotModulesAppLayoutsPublicRouteImport.update({
    id: '/_public',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotModulesAppLayoutsPanelRoute =
  DotDotModulesAppLayoutsPanelRouteImport.update({
    id: '/_panel',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/userId/',
  path: '/users/userId/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const UsersUpsertIndexRoute = UsersUpsertIndexRouteImport.update({
  id: '/users/upsert/',
  path: '/users/upsert/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const UsersUpsertUserIdRoute = UsersUpsertUserIdRouteImport.update({
  id: '/users/upsert/userId',
  path: '/users/upsert/userId',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile/': typeof ProfileIndexRoute
  '/users/': typeof UsersIndexRoute
  '/users/upsert/userId': typeof UsersUpsertUserIdRoute
  '/users/upsert/': typeof UsersUpsertIndexRoute
  '/users/userId/': typeof UsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof ProfileIndexRoute
  '/users': typeof UsersIndexRoute
  '/users/upsert/userId': typeof UsersUpsertUserIdRoute
  '/users/upsert': typeof UsersUpsertIndexRoute
  '/users/userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof DotDotModulesAppLayoutsPanelRouteWithChildren
  '/_public': typeof DotDotModulesAppLayoutsPublicRouteWithChildren
  '/_panel/about': typeof AboutRoute
  '/_public/login': typeof LoginRoute
  '/_public/register': typeof RegisterRoute
  '/_public/': typeof IndexRoute
  '/_panel/profile/': typeof ProfileIndexRoute
  '/_panel/users/': typeof UsersIndexRoute
  '/_panel/users/upsert/userId': typeof UsersUpsertUserIdRoute
  '/_panel/users/upsert/': typeof UsersUpsertIndexRoute
  '/_panel/users/userId/': typeof UsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/profile/'
    | '/users/'
    | '/users/upsert/userId'
    | '/users/upsert/'
    | '/users/userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/profile'
    | '/users'
    | '/users/upsert/userId'
    | '/users/upsert'
    | '/users/userId'
  id:
    | '__root__'
    | '/_panel'
    | '/_public'
    | '/_panel/about'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_panel/profile/'
    | '/_panel/users/'
    | '/_panel/users/upsert/userId'
    | '/_panel/users/upsert/'
    | '/_panel/users/userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotModulesAppLayoutsPanelRoute: typeof DotDotModulesAppLayoutsPanelRouteWithChildren
  DotDotModulesAppLayoutsPublicRoute: typeof DotDotModulesAppLayoutsPublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotDotModulesAppLayoutsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotDotModulesAppLayoutsPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_panel/about': {
      id: '/_panel/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/users/': {
      id: '/_panel/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/profile/': {
      id: '/_panel/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/users/userId/': {
      id: '/_panel/users/userId/'
      path: '/users/userId'
      fullPath: '/users/userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/users/upsert/': {
      id: '/_panel/users/upsert/'
      path: '/users/upsert'
      fullPath: '/users/upsert/'
      preLoaderRoute: typeof UsersUpsertIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/users/upsert/userId': {
      id: '/_panel/users/upsert/userId'
      path: '/users/upsert/userId'
      fullPath: '/users/upsert/userId'
      preLoaderRoute: typeof UsersUpsertUserIdRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
  }
}

interface DotDotModulesAppLayoutsPanelRouteChildren {
  AboutRoute: typeof AboutRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersUpsertUserIdRoute: typeof UsersUpsertUserIdRoute
  UsersUpsertIndexRoute: typeof UsersUpsertIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

const DotDotModulesAppLayoutsPanelRouteChildren: DotDotModulesAppLayoutsPanelRouteChildren =
  {
    AboutRoute: AboutRoute,
    ProfileIndexRoute: ProfileIndexRoute,
    UsersIndexRoute: UsersIndexRoute,
    UsersUpsertUserIdRoute: UsersUpsertUserIdRoute,
    UsersUpsertIndexRoute: UsersUpsertIndexRoute,
    UsersUserIdIndexRoute: UsersUserIdIndexRoute,
  }

const DotDotModulesAppLayoutsPanelRouteWithChildren =
  DotDotModulesAppLayoutsPanelRoute._addFileChildren(
    DotDotModulesAppLayoutsPanelRouteChildren,
  )

interface DotDotModulesAppLayoutsPublicRouteChildren {
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  IndexRoute: typeof IndexRoute
}

const DotDotModulesAppLayoutsPublicRouteChildren: DotDotModulesAppLayoutsPublicRouteChildren =
  {
    LoginRoute: LoginRoute,
    RegisterRoute: RegisterRoute,
    IndexRoute: IndexRoute,
  }

const DotDotModulesAppLayoutsPublicRouteWithChildren =
  DotDotModulesAppLayoutsPublicRoute._addFileChildren(
    DotDotModulesAppLayoutsPublicRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotDotModulesAppLayoutsPanelRoute:
    DotDotModulesAppLayoutsPanelRouteWithChildren,
  DotDotModulesAppLayoutsPublicRoute:
    DotDotModulesAppLayoutsPublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
