/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotModulesAppLayoutsPublicRouteImport } from './modules/app/layouts/_public'
import { Route as DotDotModulesAppLayoutsPanelRouteImport } from './modules/app/layouts/_panel'
import { Route as IndexRouteImport } from './modules/app/routes/public/index'
import { Route as TermsRouteImport } from './modules/app/routes/public/terms'
import { Route as RegisterRouteImport } from './modules/auth/routes/public/register'
import { Route as PrivacyRouteImport } from './modules/app/routes/public/privacy'
import { Route as LoginRouteImport } from './modules/auth/routes/public/login'
import { Route as FaqRouteImport } from './modules/app/routes/public/faq'
import { Route as ContactRouteImport } from './modules/app/routes/public/contact'
import { Route as AboutRouteImport } from './modules/app/routes/public/about'
import { Route as MentorVerificationsRouteImport } from './modules/app/routes/panel/mentor-verifications'
import { Route as MentorRouteImport } from './modules/app/routes/panel/mentor'
import { Route as HomeRouteImport } from './modules/app/routes/panel/home'
import { Route as DashboardRouteImport } from './modules/app/routes/panel/dashboard'
import { Route as UsersIndexRouteImport } from './modules/user/routes/index'
import { Route as ScheduleIndexRouteImport } from './modules/schedule/routes/index'
import { Route as ProfileIndexRouteImport } from './modules/auth/routes/profile/index'
import { Route as ChatsIndexRouteImport } from './modules/chat/routes/index'
import { Route as AppointmentsIndexRouteImport } from './modules/appointment/routes/index'
import { Route as AppointmentsExpertiseRouteImport } from './modules/appointment/routes/expertise'
import { Route as AppointmentsBookRouteImport } from './modules/appointment/routes/book'
import { Route as UsersUpsertIndexRouteImport } from './modules/user/routes/upsert/index'
import { Route as UsersUserIdIndexRouteImport } from './modules/user/routes/$userId/index'
import { Route as ChatsChatIdIndexRouteImport } from './modules/chat/routes/$chatId/index'
import { Route as UsersUpsertUserIdRouteImport } from './modules/user/routes/upsert/$userId'

const DotDotModulesAppLayoutsPublicRoute =
  DotDotModulesAppLayoutsPublicRouteImport.update({
    id: '/_public',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotModulesAppLayoutsPanelRoute =
  DotDotModulesAppLayoutsPanelRouteImport.update({
    id: '/_panel',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DotDotModulesAppLayoutsPublicRoute,
} as any)
const MentorVerificationsRoute = MentorVerificationsRouteImport.update({
  id: '/mentor-verifications',
  path: '/mentor-verifications',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const AppointmentsExpertiseRoute = AppointmentsExpertiseRouteImport.update({
  id: '/appointments/expertise',
  path: '/appointments/expertise',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const AppointmentsBookRoute = AppointmentsBookRouteImport.update({
  id: '/appointments/book',
  path: '/appointments/book',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const UsersUpsertIndexRoute = UsersUpsertIndexRouteImport.update({
  id: '/users/upsert/',
  path: '/users/upsert/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const ChatsChatIdIndexRoute = ChatsChatIdIndexRouteImport.update({
  id: '/chats/$chatId/',
  path: '/chats/$chatId/',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)
const UsersUpsertUserIdRoute = UsersUpsertUserIdRouteImport.update({
  id: '/users/upsert/$userId',
  path: '/users/upsert/$userId',
  getParentRoute: () => DotDotModulesAppLayoutsPanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/mentor': typeof MentorRoute
  '/mentor-verifications': typeof MentorVerificationsRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/appointments/expertise': typeof AppointmentsExpertiseRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/users/': typeof UsersIndexRoute
  '/users/upsert/$userId': typeof UsersUpsertUserIdRoute
  '/chats/$chatId/': typeof ChatsChatIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/users/upsert/': typeof UsersUpsertIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/mentor': typeof MentorRoute
  '/mentor-verifications': typeof MentorVerificationsRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/appointments/expertise': typeof AppointmentsExpertiseRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/chats': typeof ChatsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/users': typeof UsersIndexRoute
  '/users/upsert/$userId': typeof UsersUpsertUserIdRoute
  '/chats/$chatId': typeof ChatsChatIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/users/upsert': typeof UsersUpsertIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof DotDotModulesAppLayoutsPanelRouteWithChildren
  '/_public': typeof DotDotModulesAppLayoutsPublicRouteWithChildren
  '/_panel/dashboard': typeof DashboardRoute
  '/_panel/home': typeof HomeRoute
  '/_panel/mentor': typeof MentorRoute
  '/_panel/mentor-verifications': typeof MentorVerificationsRoute
  '/_public/about': typeof AboutRoute
  '/_public/contact': typeof ContactRoute
  '/_public/faq': typeof FaqRoute
  '/_public/login': typeof LoginRoute
  '/_public/privacy': typeof PrivacyRoute
  '/_public/register': typeof RegisterRoute
  '/_public/terms': typeof TermsRoute
  '/_public/': typeof IndexRoute
  '/_panel/appointments/book': typeof AppointmentsBookRoute
  '/_panel/appointments/expertise': typeof AppointmentsExpertiseRoute
  '/_panel/appointments/': typeof AppointmentsIndexRoute
  '/_panel/chats/': typeof ChatsIndexRoute
  '/_panel/profile/': typeof ProfileIndexRoute
  '/_panel/schedule/': typeof ScheduleIndexRoute
  '/_panel/users/': typeof UsersIndexRoute
  '/_panel/users/upsert/$userId': typeof UsersUpsertUserIdRoute
  '/_panel/chats/$chatId/': typeof ChatsChatIdIndexRoute
  '/_panel/users/$userId/': typeof UsersUserIdIndexRoute
  '/_panel/users/upsert/': typeof UsersUpsertIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/mentor'
    | '/mentor-verifications'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/appointments/book'
    | '/appointments/expertise'
    | '/appointments/'
    | '/chats/'
    | '/profile/'
    | '/schedule/'
    | '/users/'
    | '/users/upsert/$userId'
    | '/chats/$chatId/'
    | '/users/$userId/'
    | '/users/upsert/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/home'
    | '/mentor'
    | '/mentor-verifications'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/appointments/book'
    | '/appointments/expertise'
    | '/appointments'
    | '/chats'
    | '/profile'
    | '/schedule'
    | '/users'
    | '/users/upsert/$userId'
    | '/chats/$chatId'
    | '/users/$userId'
    | '/users/upsert'
  id:
    | '__root__'
    | '/_panel'
    | '/_public'
    | '/_panel/dashboard'
    | '/_panel/home'
    | '/_panel/mentor'
    | '/_panel/mentor-verifications'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/login'
    | '/_public/privacy'
    | '/_public/register'
    | '/_public/terms'
    | '/_public/'
    | '/_panel/appointments/book'
    | '/_panel/appointments/expertise'
    | '/_panel/appointments/'
    | '/_panel/chats/'
    | '/_panel/profile/'
    | '/_panel/schedule/'
    | '/_panel/users/'
    | '/_panel/users/upsert/$userId'
    | '/_panel/chats/$chatId/'
    | '/_panel/users/$userId/'
    | '/_panel/users/upsert/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotModulesAppLayoutsPanelRoute: typeof DotDotModulesAppLayoutsPanelRouteWithChildren
  DotDotModulesAppLayoutsPublicRoute: typeof DotDotModulesAppLayoutsPublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotDotModulesAppLayoutsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotDotModulesAppLayoutsPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPublicRoute
    }
    '/_panel/mentor-verifications': {
      id: '/_panel/mentor-verifications'
      path: '/mentor-verifications'
      fullPath: '/mentor-verifications'
      preLoaderRoute: typeof MentorVerificationsRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/mentor': {
      id: '/_panel/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/home': {
      id: '/_panel/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/dashboard': {
      id: '/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/users/': {
      id: '/_panel/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/schedule/': {
      id: '/_panel/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/profile/': {
      id: '/_panel/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/chats/': {
      id: '/_panel/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/appointments/': {
      id: '/_panel/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/appointments/expertise': {
      id: '/_panel/appointments/expertise'
      path: '/appointments/expertise'
      fullPath: '/appointments/expertise'
      preLoaderRoute: typeof AppointmentsExpertiseRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/appointments/book': {
      id: '/_panel/appointments/book'
      path: '/appointments/book'
      fullPath: '/appointments/book'
      preLoaderRoute: typeof AppointmentsBookRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/users/upsert/': {
      id: '/_panel/users/upsert/'
      path: '/users/upsert'
      fullPath: '/users/upsert/'
      preLoaderRoute: typeof UsersUpsertIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/users/$userId/': {
      id: '/_panel/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/chats/$chatId/': {
      id: '/_panel/chats/$chatId/'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId/'
      preLoaderRoute: typeof ChatsChatIdIndexRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
    '/_panel/users/upsert/$userId': {
      id: '/_panel/users/upsert/$userId'
      path: '/users/upsert/$userId'
      fullPath: '/users/upsert/$userId'
      preLoaderRoute: typeof UsersUpsertUserIdRouteImport
      parentRoute: typeof DotDotModulesAppLayoutsPanelRoute
    }
  }
}

interface DotDotModulesAppLayoutsPanelRouteChildren {
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  MentorRoute: typeof MentorRoute
  MentorVerificationsRoute: typeof MentorVerificationsRoute
  AppointmentsBookRoute: typeof AppointmentsBookRoute
  AppointmentsExpertiseRoute: typeof AppointmentsExpertiseRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersUpsertUserIdRoute: typeof UsersUpsertUserIdRoute
  ChatsChatIdIndexRoute: typeof ChatsChatIdIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
  UsersUpsertIndexRoute: typeof UsersUpsertIndexRoute
}

const DotDotModulesAppLayoutsPanelRouteChildren: DotDotModulesAppLayoutsPanelRouteChildren =
  {
    DashboardRoute: DashboardRoute,
    HomeRoute: HomeRoute,
    MentorRoute: MentorRoute,
    MentorVerificationsRoute: MentorVerificationsRoute,
    AppointmentsBookRoute: AppointmentsBookRoute,
    AppointmentsExpertiseRoute: AppointmentsExpertiseRoute,
    AppointmentsIndexRoute: AppointmentsIndexRoute,
    ChatsIndexRoute: ChatsIndexRoute,
    ProfileIndexRoute: ProfileIndexRoute,
    ScheduleIndexRoute: ScheduleIndexRoute,
    UsersIndexRoute: UsersIndexRoute,
    UsersUpsertUserIdRoute: UsersUpsertUserIdRoute,
    ChatsChatIdIndexRoute: ChatsChatIdIndexRoute,
    UsersUserIdIndexRoute: UsersUserIdIndexRoute,
    UsersUpsertIndexRoute: UsersUpsertIndexRoute,
  }

const DotDotModulesAppLayoutsPanelRouteWithChildren =
  DotDotModulesAppLayoutsPanelRoute._addFileChildren(
    DotDotModulesAppLayoutsPanelRouteChildren,
  )

interface DotDotModulesAppLayoutsPublicRouteChildren {
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  IndexRoute: typeof IndexRoute
}

const DotDotModulesAppLayoutsPublicRouteChildren: DotDotModulesAppLayoutsPublicRouteChildren =
  {
    AboutRoute: AboutRoute,
    ContactRoute: ContactRoute,
    FaqRoute: FaqRoute,
    LoginRoute: LoginRoute,
    PrivacyRoute: PrivacyRoute,
    RegisterRoute: RegisterRoute,
    TermsRoute: TermsRoute,
    IndexRoute: IndexRoute,
  }

const DotDotModulesAppLayoutsPublicRouteWithChildren =
  DotDotModulesAppLayoutsPublicRoute._addFileChildren(
    DotDotModulesAppLayoutsPublicRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotDotModulesAppLayoutsPanelRoute:
    DotDotModulesAppLayoutsPanelRouteWithChildren,
  DotDotModulesAppLayoutsPublicRoute:
    DotDotModulesAppLayoutsPublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
