export {
  bookAppointment,
  cancelAppointment,
  getAdminStats,
  getAreasOfExpertise,
  getAvailableSlots,
  getMentorProfile,
  getMentorsForArea,
  getMyAppointments,
  getMyExpertise,
  joinAppointmentMeeting,
  rateAppointment,
  updateAppointmentStatus,
  updateMyExpertise,
} from '@/modules/appointment/services/appointment.service'
